### ISSUE TITLE
Task-dependencies

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#11]
I would like to return to the topic of task-dependencies.

Wouldn't they solve the classic problem of running e.g. tests of different abstraction layers after each other? And skip one layer if the underlying layer has failures?

Whats with cases like: run my integration tests after all my unit tests succeeded? 
Or: Skip all my integration tests if unit tests failed, as they are most likely to fail anyway?

What do you think?

**Comment by DrTom** [comment]
I recapitulate what we discussed: for the time being I see no use case where the benefit would outweigh the complexity introduced by task dependencies. In your case splitting the tasks up in to two jobs "integration tests" and "unit tests" (or something alike) and have the first one depend on the second would even be a better solution. This is possible since version 3.0.
