### ISSUE TITLE
Github notifications are using internal ip of CI

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#19]
Our CI has an internal IP (AWS internal) and a public facing IP.

In Github notifications we see the internal IP. 
Maybe that could be fixed to contain the public IP/hostname/domain or I suggest to remove it completely, as there is no case for running Cider Master redundant, isn't it?

![screen shot 2015-10-22 at 09 40 36](https://cloud.githubusercontent.com/assets/851393/10659586/3f2d9f7a-78a1-11e5-8f99-8a1709620b88.png)

**Comment by pape-io** [comment]
Just discovered that also the Links (to jump to the test result) contains the internal ip, therefore no page found when following Test results via Github.

**Comment by DrTom** [comment]
This is due to a miss(ed) configuration, it should look like this: 

<img width="519" alt="screen shot 2015-10-22 at 09 46 53" src="https://cloud.githubusercontent.com/assets/526053/10659702/f68ea560-78a1-11e5-82a5-7386106de18f.png">

I guess this is another area where the documentation is a bit to sparse.

**Comment by pape-io** [comment]
Ok I will check that out. Thx

**Comment by pape-io** [comment]
Adding the `server_http_host_name` to the `host_vars/server.yml` actually fixed that problem :+1:
